server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
spring:
  application:
    name: leyou-service
  datasource:
    url: jdbc:mysql://192.168.1.2:3307/leyou
    #url: jdbc:mysql://10.0.3.227:3306/leyou?serverTimezone=CST
    username: root
    password: abc123
mybatis:
  type-aliases-package: cn.zak.leyou.item.pojo
